# Generated by Django 3.2.8 on 2021-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.TextField(blank=True),
        ),
    ]
