# Generated by Django 3.2.8 on 2021-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_alter_statusmessage_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
